# Keep this conservative to start; you can tighten later.
strict: true

included:
  - apps/macos
  - apps/macos-ui
  - service/macos-service

excluded:
  - apps/macos-ui/Generated
  - build
  - core
  - web
  - docs
  - locales

# Good defaults: avoid wars over whitespace early on.
disabled_rules:
  - trailing_whitespace
  - line_length

opt_in_rules:
  - empty_count
  - implicit_return
