# Keep this conservative to start; you can tighten later.
strict: true

included:
  - apps/macos
  - apps/macos-ui
  - service/macos-service

excluded:
  - apps/macos-ui/Generated
  - build
  - core
  - web
  - docs
  - locales

# Good defaults: avoid wars over whitespace early on.
disabled_rules:
  - trailing_whitespace
  - line_length
  - nesting
  - trailing_comma
  - implicit_return
  - multiple_closures_with_trailing_closure
  - for_where
  - large_tuple
  - opening_brace

opt_in_rules:
  - empty_count

# Thresholds tightened after DashboardView/HelmCore file splits.
type_body_length:
  warning: 700
  error: 900

file_length:
  warning: 1300
  error: 1600

function_body_length:
  warning: 100
  error: 140

cyclomatic_complexity:
  warning: 31
  error: 45

function_parameter_count:
  warning: 12
  error: 16

identifier_name:
  min_length:
    warning: 1
  max_length:
    warning: 60
  allowed_symbols:
    - _
  excluded:
    - id
    - s
