#!/bin/bash
set -e

echo "Building Rust core..."

# Go to repo root
REPO_ROOT=$(git rev-parse --show-toplevel)
cd "$REPO_ROOT/core/rust"

# Determine build profile
if [ "$CONFIGURATION" = "Release" ]; then
    PROFILE="release"
    CARGO_FLAGS="--release"
else
    PROFILE="debug"
    CARGO_FLAGS=""
fi

# Build
cargo build -p helm-ffi $CARGO_FLAGS

# Copy artifacts to a build directory inside apps/macos-ui
# ensuring Xcode can find them
DEST_DIR="$REPO_ROOT/apps/macos-ui/Generated"
mkdir -p "$DEST_DIR"

cp "target/$PROFILE/libhelm_ffi.a" "$DEST_DIR/"
cp "crates/helm-ffi/include/helm.h" "$DEST_DIR/"

# Extract version from workspace Cargo.toml and generate Swift constant
VERSION=$(grep '^version' Cargo.toml | head -1 | sed 's/.*"\(.*\)".*/\1/')
cat > "$DEST_DIR/HelmVersion.swift" <<SWIFT
// Auto-generated by build_rust.sh — do not edit
let helmVersion = "$VERSION"
SWIFT

# Generate xcconfig for Xcode bundle version synchronization
# Strip prerelease tag for MARKETING_VERSION (Apple requires X.Y.Z)
MARKETING_VERSION=$(echo "$VERSION" | sed 's/-.*//')
# Extract build number from prerelease tag (e.g. alpha.1 -> 1); default to 0
BUILD_NUMBER=$(echo "$VERSION" | sed -n 's/.*\.\([0-9][0-9]*\)$/\1/p')
BUILD_NUMBER=${BUILD_NUMBER:-0}
cat > "$DEST_DIR/HelmVersion.xcconfig" <<XCCONFIG
// Auto-generated by build_rust.sh — do not edit
MARKETING_VERSION = $MARKETING_VERSION
CURRENT_PROJECT_VERSION = $BUILD_NUMBER
XCCONFIG

echo "Rust build complete (v$VERSION). Artifacts in $DEST_DIR"
