#!/bin/bash
set -euo pipefail

if [ $# -ne 1 ]; then
    echo "Usage: $0 <output-xcconfig-path>" >&2
    exit 1
fi

OUTPUT_PATH="$1"
REPO_ROOT=$(git rev-parse --show-toplevel)

normalize_xcconfig_bool() {
    case "$(printf '%s' "$1" | tr '[:upper:]' '[:lower:]')" in
        1|true|yes|on)
            echo "YES"
            ;;
        *)
            echo "NO"
            ;;
    esac
}

trim_xcconfig_value() {
    printf '%s' "$1" | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//'
}

read_xcconfig_value() {
    local xcconfig_file="$1"
    local key="$2"
    awk -F '=' -v key="$key" '
        $1 ~ "^[[:space:]]*" key "[[:space:]]*$" {
            value = $2
            sub(/[[:space:]]*\/\/.*/, "", value)
            sub(/^[[:space:]]+/, "", value)
            sub(/[[:space:]]+$/, "", value)
            print value
            found = 1
            exit
        }
        END {
            if (!found) {
                print ""
            }
        }
    ' "$xcconfig_file"
}

CHANNEL_PROFILE="${HELM_CHANNEL_PROFILE:-developer_id}"
CHANNEL_CONFIG_DIR="$REPO_ROOT/apps/macos-ui/Config/channels"
CHANNEL_TEMPLATE="$CHANNEL_CONFIG_DIR/${CHANNEL_PROFILE}.xcconfig"
if [ ! -f "$CHANNEL_TEMPLATE" ]; then
    echo "Unknown HELM_CHANNEL_PROFILE '$CHANNEL_PROFILE' (expected developer_id, app_store, setapp, or fleet)." >&2
    exit 1
fi

CHANNEL_DISTRIBUTION=$(trim_xcconfig_value "$(read_xcconfig_value "$CHANNEL_TEMPLATE" HELM_DISTRIBUTION_CHANNEL)")
CHANNEL_SPARKLE_ENABLED=$(normalize_xcconfig_bool "$(read_xcconfig_value "$CHANNEL_TEMPLATE" HELM_SPARKLE_ENABLED)")
CHANNEL_SPARKLE_FEED_URL=$(trim_xcconfig_value "$(read_xcconfig_value "$CHANNEL_TEMPLATE" HELM_SPARKLE_FEED_URL)")
CHANNEL_SPARKLE_PUBLIC_ED_KEY=$(trim_xcconfig_value "$(read_xcconfig_value "$CHANNEL_TEMPLATE" HELM_SPARKLE_PUBLIC_ED_KEY)")

if [ -n "${HELM_CHANNEL_OVERRIDE_DISTRIBUTION:-}" ]; then
    CHANNEL_DISTRIBUTION=$(trim_xcconfig_value "$HELM_CHANNEL_OVERRIDE_DISTRIBUTION")
fi
if [ -n "${HELM_CHANNEL_OVERRIDE_SPARKLE_ENABLED:-}" ]; then
    CHANNEL_SPARKLE_ENABLED=$(normalize_xcconfig_bool "$HELM_CHANNEL_OVERRIDE_SPARKLE_ENABLED")
fi
if [ -n "${HELM_CHANNEL_OVERRIDE_SPARKLE_FEED_URL:-}" ]; then
    CHANNEL_SPARKLE_FEED_URL=$(trim_xcconfig_value "$HELM_CHANNEL_OVERRIDE_SPARKLE_FEED_URL")
fi
if [ -n "${HELM_CHANNEL_OVERRIDE_SPARKLE_PUBLIC_ED_KEY:-}" ]; then
    CHANNEL_SPARKLE_PUBLIC_ED_KEY=$(trim_xcconfig_value "$HELM_CHANNEL_OVERRIDE_SPARKLE_PUBLIC_ED_KEY")
fi

if [ "$CHANNEL_DISTRIBUTION" != "developer_id" ]; then
    if [ "$CHANNEL_SPARKLE_ENABLED" = "YES" ]; then
        echo "Invalid channel config: Sparkle must be disabled when HELM_DISTRIBUTION_CHANNEL=$CHANNEL_DISTRIBUTION." >&2
        exit 1
    fi
    if [ -n "$CHANNEL_SPARKLE_FEED_URL" ] || [ -n "$CHANNEL_SPARKLE_PUBLIC_ED_KEY" ]; then
        echo "Invalid channel config: Sparkle feed/signing metadata must be empty for non-developer channels ($CHANNEL_DISTRIBUTION)." >&2
        exit 1
    fi
fi

if [ "$CHANNEL_DISTRIBUTION" = "developer_id" ] && [ "$CHANNEL_SPARKLE_ENABLED" = "YES" ]; then
    if [ -z "$CHANNEL_SPARKLE_FEED_URL" ] || [ -z "$CHANNEL_SPARKLE_PUBLIC_ED_KEY" ]; then
        echo "Invalid channel config: Developer ID channel with Sparkle enabled requires HELM_SPARKLE_FEED_URL and HELM_SPARKLE_PUBLIC_ED_KEY." >&2
        exit 1
    fi
fi

cat > "$OUTPUT_PATH" <<XCCONFIG
// Auto-generated by render_channel_xcconfig.sh — do not edit
HELM_DISTRIBUTION_CHANNEL = $CHANNEL_DISTRIBUTION
HELM_SPARKLE_ENABLED = $CHANNEL_SPARKLE_ENABLED
HELM_SPARKLE_FEED_URL = $CHANNEL_SPARKLE_FEED_URL
HELM_SPARKLE_PUBLIC_ED_KEY = $CHANNEL_SPARKLE_PUBLIC_ED_KEY
XCCONFIG
