import Foundation

@objc public protocol HelmServiceProtocol {
    func listInstalledPackages(withReply reply: @escaping (String?) -> Void)
    func listOutdatedPackages(withReply reply: @escaping (String?) -> Void)
    func listTasks(withReply reply: @escaping (String?) -> Void)
    func getTaskOutput(taskId: Int64, withReply reply: @escaping (String?) -> Void)
    func listTaskLogs(taskId: Int64, limit: Int64, withReply reply: @escaping (String?) -> Void)
    func triggerRefresh(withReply reply: @escaping (Bool) -> Void)
    func triggerDetection(withReply reply: @escaping (Bool) -> Void)
    func searchLocal(query: String, withReply reply: @escaping (String?) -> Void)
    func triggerRemoteSearch(query: String, withReply reply: @escaping (Int64) -> Void)
    func triggerRemoteSearchForManager(managerId: String, query: String, withReply reply: @escaping (Int64) -> Void)
    func cancelTask(taskId: Int64, withReply reply: @escaping (Bool) -> Void)
    func listManagerStatus(withReply reply: @escaping (String?) -> Void)
    func getSafeMode(withReply reply: @escaping (Bool) -> Void)
    func setSafeMode(enabled: Bool, withReply reply: @escaping (Bool) -> Void)
    func getHomebrewKegAutoCleanup(withReply reply: @escaping (Bool) -> Void)
    func setHomebrewKegAutoCleanup(enabled: Bool, withReply reply: @escaping (Bool) -> Void)
    func listPackageKegPolicies(withReply reply: @escaping (String?) -> Void)
    func setPackageKegPolicy(managerId: String, packageName: String, policyMode: Int32, withReply reply: @escaping (Bool) -> Void)
    func previewUpgradePlan(includePinned: Bool, allowOsUpdates: Bool, withReply reply: @escaping (String?) -> Void)
    func upgradeAll(includePinned: Bool, allowOsUpdates: Bool, withReply reply: @escaping (Bool) -> Void)
    func upgradePackage(managerId: String, packageName: String, withReply reply: @escaping (Int64) -> Void)
    func installPackage(managerId: String, packageName: String, withReply reply: @escaping (Int64) -> Void)
    func uninstallPackage(managerId: String, packageName: String, withReply reply: @escaping (Int64) -> Void)
    func listPins(withReply reply: @escaping (String?) -> Void)
    func pinPackage(managerId: String, packageName: String, version: String?, withReply reply: @escaping (Bool) -> Void)
    func unpinPackage(managerId: String, packageName: String, withReply reply: @escaping (Bool) -> Void)
    func setManagerEnabled(managerId: String, enabled: Bool, withReply reply: @escaping (Bool) -> Void)
    func setManagerSelectedExecutablePath(managerId: String, selectedPath: String?, withReply reply: @escaping (Bool) -> Void)
    func setManagerInstallMethod(managerId: String, installMethod: String?, withReply reply: @escaping (Bool) -> Void)
    func installManager(managerId: String, withReply reply: @escaping (Int64) -> Void)
    func updateManager(managerId: String, withReply reply: @escaping (Int64) -> Void)
    func uninstallManager(managerId: String, withReply reply: @escaping (Int64) -> Void)
    func resetDatabase(withReply reply: @escaping (Bool) -> Void)
    func takeLastErrorKey(withReply reply: @escaping (String?) -> Void)
}
